language: node_js
node_js: ['node', 8, 7, 6, 5, 4]
env:
    - NODE_ENVIRONMENT=production

deploy:
  on:
      tags: true
      branch: master
      node_js: '8'
  skip_cleanup: true
  provider: npm
  email: foo
  api_key: foo
